# Generated by Django 4.1.1 on 2023-02-05 19:24

from django.db import migrations, models
import musicapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=musicapi.models.generate_unique_code, max_length=8, unique=True),
        ),
    ]
