# Generated by Django 4.1.1 on 2023-02-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0002_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
